[2021-03-19 13:36:59,143.143] login_test.py -> setup_class:26 [INFO] : Initialize
[2021-03-19 13:37:21,608.608] login_test.py -> test_login:46 [INFO] : perform test_login case <case:test_login>
[2021-03-19 13:37:21,609.609] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 13:37:21,732.732] login_business.py -> login_in:25 [INFO] : input password <case:test_login>
[2021-03-19 13:37:22,415.415] login_business.py -> login_in:28 [INFO] : click login button <case:test_login>
[2021-03-19 13:37:24,263.263] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->1 time <case:test_login>
[2021-03-19 13:37:36,044.44] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->2 time <case:test_login>
[2021-03-19 13:37:47,753.753] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->3 time <case:test_login>
[2021-03-19 13:37:59,481.481] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->4 time <case:test_login>
[2021-03-19 13:38:11,187.187] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->5 time <case:test_login>
[2021-03-19 13:38:13,202.202] login_handler.py -> slide_verify_btn:40 [INFO] : Traceback (most recent call last):
  File "../Handler/login_handler.py", line 31, in slide_verify_btn
    slide_bar = self.driver.get_verify_element()
  File "../Page/login_page.py", line 36, in get_verify_element
    return self.fe.find_element('login_verify_slideBar')
  File "../tools/find_elements.py", line 14, in find_element
    return self.driver.find_element_by_xpath(data[1])
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='tcaptcha_drag_thumb']"}
  (Session info: chrome=89.0.4389.90)


[2021-03-19 13:38:13,874.874] login_test.py -> teardown_class:39 [INFO] : End of test! TearDown!
[2021-03-19 14:18:45,288.288] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 14:19:57,136.136] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 14:20:19,193.193] login_relogin_test.py -> test_login:39 [INFO] : perform test_login case <case:test_login>
[2021-03-19 14:20:19,193.193] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 14:20:19,275.275] login_business.py -> login_in:25 [INFO] : input password <case:test_login>
[2021-03-19 14:20:19,945.945] login_business.py -> login_in:28 [INFO] : click login button <case:test_login>
[2021-03-19 14:20:21,636.636] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->1 time <case:test_login>
[2021-03-19 14:20:33,421.421] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->2 time <case:test_login>
[2021-03-19 14:20:45,129.129] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->3 time <case:test_login>
[2021-03-19 14:20:47,136.136] login_handler.py -> slide_verify_btn:40 [INFO] : Traceback (most recent call last):
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Handler/login_handler.py", line 31, in slide_verify_btn
    slide_bar = self.driver.get_verify_element()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 36, in get_verify_element
    return self.fe.find_element('login_verify_slideBar')
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/tools/find_elements.py", line 14, in find_element
    return self.driver.find_element_by_xpath(data[1])
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=89.0.4389.90)


[2021-03-19 14:20:47,140.140] login_business.py -> login_in:36 [ERROR] : Traceback (most recent call last):
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/business/login_business.py", line 33, in login_in
    screenshot().save_rt_screenshot(driver=self.driver, file_name='登陆成功.png')
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/util/save_screenshot.py", line 28, in save_rt_screenshot
    driver.save_screenshot(file_path)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=89.0.4389.90)


[2021-03-19 14:20:47,195.195] login_relogin_test.py -> teardown_class:31 [INFO] : End of test! TearDown!
[2021-03-19 14:20:55,383.383] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 14:21:17,890.890] login_relogin_test.py -> test_login:39 [INFO] : perform test_login case <case:test_login>
[2021-03-19 14:21:17,890.890] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 14:21:17,970.970] login_business.py -> login_in:25 [INFO] : input password <case:test_login>
[2021-03-19 14:21:18,652.652] login_business.py -> login_in:28 [INFO] : click login button <case:test_login>
[2021-03-19 14:21:20,506.506] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->1 time <case:test_login>
[2021-03-19 14:21:55,857.857] login_business.py -> login_in:23 [INFO] : input username <case:test_login1>
[2021-03-19 14:21:55,945.945] login_business.py -> login_in:25 [INFO] : input password <case:test_login1>
[2021-03-19 14:21:56,585.585] login_business.py -> login_in:28 [INFO] : click login button <case:test_login1>
[2021-03-19 14:21:58,323.323] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->1 time <case:test_login1>
[2021-03-19 14:22:10,075.75] login_handler.py -> slide_verify_btn:28 [INFO] : start to login verify ---->2 time <case:test_login1>
[2021-03-19 14:22:12,090.90] login_handler.py -> slide_verify_btn:40 [INFO] : Traceback (most recent call last):
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Handler/login_handler.py", line 31, in slide_verify_btn
    slide_bar = self.driver.get_verify_element()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 36, in get_verify_element
    return self.fe.find_element('login_verify_slideBar')
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/tools/find_elements.py", line 14, in find_element
    return self.driver.find_element_by_xpath(data[1])
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='tcaptcha_drag_thumb']"}
  (Session info: chrome=89.0.4389.90)


[2021-03-19 14:22:12,714.714] login_relogin_test.py -> teardown_class:31 [INFO] : End of test! TearDown!
[2021-03-19 14:28:46,914.914] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 14:29:08,662.662] login_relogin_test.py -> test_login:39 [INFO] : perform test_login case <case:test_login>
[2021-03-19 14:29:08,663.663] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 14:29:08,763.763] login_business.py -> login_in:25 [INFO] : input password <case:test_login>
[2021-03-19 14:29:09,399.399] login_business.py -> login_in:28 [INFO] : click login button <case:test_login>
[2021-03-19 14:29:11,148.148] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->1 time <case:test_login>
[2021-03-19 14:29:22,911.911] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->2 time <case:test_login>
[2021-03-19 14:29:34,618.618] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->3 time <case:test_login>
[2021-03-19 14:30:07,400.400] login_business.py -> login_in:23 [INFO] : input username <case:test_login1>
[2021-03-19 14:30:07,505.505] login_business.py -> login_in:25 [INFO] : input password <case:test_login1>
[2021-03-19 14:30:08,142.142] login_business.py -> login_in:28 [INFO] : click login button <case:test_login1>
[2021-03-19 14:30:09,820.820] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->1 time <case:test_login1>
[2021-03-19 14:30:22,959.959] login_relogin_test.py -> teardown_class:31 [INFO] : End of test! TearDown!
[2021-03-19 14:41:31,609.609] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 14:41:53,659.659] login_relogin_test.py -> test_login:40 [INFO] : perform test_login case <case:test_login>
[2021-03-19 14:41:53,660.660] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 14:41:53,769.769] login_business.py -> login_in:25 [INFO] : input password <case:test_login>
[2021-03-19 14:41:54,446.446] login_business.py -> login_in:28 [INFO] : click login button <case:test_login>
[2021-03-19 14:41:56,163.163] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->1 time <case:test_login>
[2021-03-19 14:42:10,299.299] login_relogin_test.py -> test_logout:49 [INFO] : perform test_logout case <case:test_logout>
[2021-03-19 14:42:10,300.300] main_business.py -> logout:22 [INFO] : click logout button
[2021-03-19 14:42:12,893.893] main_business.py -> logout:25 [INFO] : click relogin button
[2021-03-19 14:42:29,174.174] login_relogin_test.py -> test_login1:56 [INFO] : perform test_login case again <case:test_login>
[2021-03-19 14:42:29,174.174] login_business.py -> login_in:23 [INFO] : input username <case:test_login1>
[2021-03-19 14:42:29,181.181] login_business.py -> login_in:36 [ERROR] : Traceback (most recent call last):
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/business/login_business.py", line 24, in login_in
    log_in.send_username(self._username)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Handler/login_handler.py", line 17, in send_username
    ur_element = self.driver.get_username_element()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 23, in get_username_element
    self.__switch_to_login_frame__()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 12, in __switch_to_login_frame__
    a = self.fe.find_element('login_frame')
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/tools/find_elements.py", line 14, in find_element
    return self.driver.find_element_by_xpath(data[1])
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//iframe[@id='login_frame']"}
  (Session info: chrome=89.0.4389.90)


[2021-03-19 14:42:29,265.265] login_relogin_test.py -> teardown_class:32 [INFO] : End of test! TearDown!
[2021-03-19 14:46:44,120.120] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 14:47:06,139.139] login_relogin_test.py -> test_login:40 [INFO] : perform test_login case <case:test_login>
[2021-03-19 14:47:06,139.139] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 14:47:06,241.241] login_business.py -> login_in:25 [INFO] : input password <case:test_login>
[2021-03-19 14:47:06,903.903] login_business.py -> login_in:28 [INFO] : click login button <case:test_login>
[2021-03-19 14:47:08,587.587] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->1 time <case:test_login>
[2021-03-19 14:47:20,369.369] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->2 time <case:test_login>
[2021-03-19 14:47:35,258.258] login_relogin_test.py -> test_logout:49 [INFO] : perform test_logout case <case:test_logout>
[2021-03-19 14:47:35,258.258] main_business.py -> logout:22 [INFO] : click logout button
[2021-03-19 14:47:37,514.514] main_business.py -> logout:25 [INFO] : click relogin button
[2021-03-19 14:47:53,814.814] login_relogin_test.py -> test_login1:56 [INFO] : perform test_login case again <case:test_login>
[2021-03-19 14:47:55,815.815] login_business.py -> login_in:23 [INFO] : input username <case:test_login1>
[2021-03-19 14:47:55,825.825] login_business.py -> login_in:36 [ERROR] : Traceback (most recent call last):
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/business/login_business.py", line 24, in login_in
    log_in.send_username(self._username)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Handler/login_handler.py", line 17, in send_username
    ur_element = self.driver.get_username_element()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 23, in get_username_element
    self.__switch_to_login_frame__()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 12, in __switch_to_login_frame__
    a = self.fe.find_element('login_frame')
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/tools/find_elements.py", line 14, in find_element
    return self.driver.find_element_by_xpath(data[1])
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//iframe[@id='login_frame']"}
  (Session info: chrome=89.0.4389.90)


[2021-03-19 14:47:55,910.910] login_relogin_test.py -> teardown_class:32 [INFO] : End of test! TearDown!
[2021-03-19 14:52:58,684.684] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 14:53:20,754.754] login_relogin_test.py -> test_login:40 [INFO] : perform test_login case <case:test_login>
[2021-03-19 14:53:20,754.754] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 14:53:20,763.763] login_business.py -> login_in:36 [ERROR] : Traceback (most recent call last):
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/business/login_business.py", line 24, in login_in
    log_in.send_username(self._username)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Handler/login_handler.py", line 17, in send_username
    ur_element = self.driver.get_username_element()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 24, in get_username_element
    return self.fe.find_element('login_name')
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/tools/find_elements.py", line 14, in find_element
    return self.driver.find_element_by_xpath(data[1])
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='u']"}
  (Session info: chrome=89.0.4389.90)


[2021-03-19 14:53:20,835.835] login_relogin_test.py -> test_logout:49 [INFO] : perform test_logout case <case:test_logout>
[2021-03-19 14:53:20,836.836] main_business.py -> logout:22 [INFO] : click logout button
[2021-03-19 14:53:20,884.884] login_relogin_test.py -> test_login1:56 [INFO] : perform test_login case again <case:test_login>
[2021-03-19 14:53:22,889.889] login_business.py -> login_in:23 [INFO] : input username <case:test_login1>
[2021-03-19 14:53:22,897.897] login_business.py -> login_in:36 [ERROR] : Traceback (most recent call last):
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/business/login_business.py", line 24, in login_in
    log_in.send_username(self._username)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Handler/login_handler.py", line 17, in send_username
    ur_element = self.driver.get_username_element()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 24, in get_username_element
    return self.fe.find_element('login_name')
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/tools/find_elements.py", line 14, in find_element
    return self.driver.find_element_by_xpath(data[1])
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='u']"}
  (Session info: chrome=89.0.4389.90)


[2021-03-19 14:53:22,938.938] login_relogin_test.py -> teardown_class:32 [INFO] : End of test! TearDown!
[2021-03-19 14:56:03,294.294] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 14:56:24,977.977] login_relogin_test.py -> test_login:40 [INFO] : perform test_login case <case:test_login>
[2021-03-19 14:56:24,977.977] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 14:56:25,077.77] login_business.py -> login_in:25 [INFO] : input password <case:test_login>
[2021-03-19 14:56:25,736.736] login_business.py -> login_in:28 [INFO] : click login button <case:test_login>
[2021-03-19 14:56:27,452.452] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->1 time <case:test_login>
[2021-03-19 14:56:54,966.966] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->2 time <case:test_login>
[2021-03-19 14:57:21,767.767] login_handler.py -> slide_verify_btn:33 [INFO] : start to login verify ---->3 time <case:test_login>
[2021-03-19 14:57:38,930.930] login_relogin_test.py -> test_logout:49 [INFO] : perform test_logout case <case:test_logout>
[2021-03-19 14:57:38,930.930] main_business.py -> logout:22 [INFO] : click logout button
[2021-03-19 14:57:43,142.142] main_business.py -> logout:25 [INFO] : click relogin button
[2021-03-19 14:57:59,436.436] login_relogin_test.py -> test_login1:56 [INFO] : perform test_login case again <case:test_login>
[2021-03-19 14:58:01,439.439] login_business.py -> login_in:23 [INFO] : input username <case:test_login1>
[2021-03-19 14:58:01,449.449] login_business.py -> login_in:36 [ERROR] : Traceback (most recent call last):
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/business/login_business.py", line 24, in login_in
    log_in.send_username(self._username)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Handler/login_handler.py", line 17, in send_username
    ur_element = self.driver.get_username_element()
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/Page/login_page.py", line 26, in get_username_element
    return self.fe.find_element('login_name')
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/tools/find_elements.py", line 14, in find_element
    return self.driver.find_element_by_xpath(data[1])
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chenrongtao/PycharmProjects/QQMail-EmptyTrash/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='u']"}
  (Session info: chrome=89.0.4389.90)


[2021-03-19 14:58:01,490.490] login_relogin_test.py -> teardown_class:32 [INFO] : End of test! TearDown!
[2021-03-19 15:05:36,869.869] login_relogin_test.py -> setup_class:16 [INFO] : Initialize
[2021-03-19 15:05:58,883.883] login_relogin_test.py -> test_login:40 [INFO] : perform test_login case <case:test_login>
[2021-03-19 15:05:58,883.883] login_business.py -> login_in:23 [INFO] : input username <case:test_login>
[2021-03-19 15:05:58,980.980] login_business.py -> login_in:25 [INFO] : input password <case:test_login>
[2021-03-19 15:05:59,643.643] login_business.py -> login_in:28 [INFO] : click login button <case:test_login>
[2021-03-19 15:06:01,316.316] login_handler.py -> slide_verify_btn:35 [INFO] : start to login verify ---->1 time <case:test_login>
[2021-03-19 15:06:17,077.77] login_relogin_test.py -> test_logout:49 [INFO] : perform test_logout case <case:test_logout>
[2021-03-19 15:06:17,078.78] main_business.py -> logout:22 [INFO] : click logout button
[2021-03-19 15:06:20,922.922] main_business.py -> logout:25 [INFO] : click relogin button
[2021-03-19 15:06:37,213.213] login_relogin_test.py -> test_login1:56 [INFO] : perform test_login case again <case:test_login>
[2021-03-19 15:06:39,216.216] login_business.py -> login_in:23 [INFO] : input username <case:test_login1>
[2021-03-19 15:06:39,336.336] login_business.py -> login_in:25 [INFO] : input password <case:test_login1>
[2021-03-19 15:06:39,997.997] login_business.py -> login_in:28 [INFO] : click login button <case:test_login1>
[2021-03-19 15:06:41,754.754] login_handler.py -> slide_verify_btn:35 [INFO] : start to login verify ---->1 time <case:test_login1>
[2021-03-19 15:06:54,879.879] login_relogin_test.py -> teardown_class:32 [INFO] : End of test! TearDown!
